### ISSUE TITLE
Are there Real UseCase with Converter?

### ISSUE THREAD

**Issue by the-red** [almin/ddd-base#22]
All three of the following Real UseCases use the `Silializer`, but they are deprecated.

* azu/irodr: RSS reader client like LDR for Inoreader.
* azu/searchive: Search All My Documents{PDF}.
* proofdict/editor: Proofdict editor.

I would like examples Real UseCases with `Converter`.

**Comment by azu** [comment]
`Convert` example is only https://github.com/almin/ddd-base/blob/master/test/Converter-test.ts.
ddd-base is very experimental.

**Comment by the-red** [comment]
I Got it.
Thank you!
